<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert(
            [
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 1,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 2,
                    'can_read' => 3,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 3,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 4,
                    'can_read' => 0,
                    'can_create' => 0,
                    'can_update' => 0,
                    'can_delete' => 0,
                    'can_delete' => 0,
                    'access' => 0,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 5,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 6,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 7,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 8,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 9,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 10,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 11,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 12,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 13,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 14,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 15,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 16,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 17,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 18,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 19,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 20,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 21,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 22,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 23,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 24,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 25,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 26,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 27,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 28,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 29,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 30,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 31,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 32,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 33,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 34,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 35,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
                [
                    'roles_id' => 1,
                    'sub_categories_id' => 36,
                    'can_read' => 1,
                    'can_create' => 1,
                    'can_update' => 1,
                    'can_delete' => 1,
                    'can_delete' => 1,
                    'access' => 1,
                ],
            ]
        );
    }
}
